services:
  load_balancer:
    container_name: load_balancer
    build:
      context: ./load_balancer
      dockerfile: Dockerfile
    working_dir: /app
    command: gunicorn --bind 0.0.0.0:5000 app:app --log-level debug
    ports:
      - "5000:5000"
    networks:
      - lb_network
    depends_on:
      - server1
      - server2
      - server3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  server1:
    container_name: server1
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myserver:latest
    environment:
      - SERVER_ID=1
    networks:
      - lb_network
  server2:
    container_name: server2
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myserver:latest
    environment:
      - SERVER_ID=2
    networks:
      - lb_network
  server3:
    container_name: server3
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myserver:latest
    environment:
      - SERVER_ID=3
    networks:
      - lb_network
networks:
  lb_network:
    name: lb_network
    driver: bridge